# -*- coding: utf-8 -*-
"""ohlcExtract

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zbkNCoYwhLb-nYP2dY1RjFwrC5hrVTpk
"""

import sys
import pandas as pd
import numpy as np
import datetime as dt

#到期日=第三個星期三
def compute_third_wed(y,m):
	day = 21 - (dt.date(y, m, 1).weekday() + 4) % 7		# dt.date function find the third weekday of the month, mon=0, sun=6
	return str(dt.date(y,m,day)).split('-')[-1]       # 將傳回值型態由datetime.frame轉換成string, 同時split擷取最後代表幾號的day

#main function
def main():

	#---file handling---#
	try: filename = str(sys.argv[1])
	except: raise ValueError('please enter a file path!')


	#---read data---#
	df = pd.read_csv(filename, 
					encoding='big5',
					dtype=str,
					low_memory=True)
	date = df['成交日期'].values
	p_id = df['商品代號'].values
	due_month = df['到期月份(週別)'].values
	time = df['成交時間'].values
	price = df['成交價格'].values
	del df


	#---compute date---#
	for i, d in enumerate(date):
		date[i] = d.strip()
	date = np.amax(date)
	
	duemonth = int(date[0:6])
	third_wed = int(compute_third_wed(int(date[0:4]), int(date[4:6])))
	if int(date[6:]) > third_wed:
		duemonth += 1


	#---parse data---#
	data = []
	for i in range(len(p_id)):
		if str(p_id[i].strip()) == 'TX':     #取台指期TX
			try:
				if int(due_month[i].strip()) == duemonth:
					if int(time[i].strip()) >= 84500 and int(time[i].strip()) <= 134500:  #只取盤內交易時間內的交易
						data.append(int(price[i]))
			except:
				pass


	#---compute OHLC---#
	openprice = data[0]
	highprice = np.amax(data)
	lowprice = np.amin(data)
	closeprice = data[-1]
	print(openprice, highprice, lowprice, closeprice)


if __name__ == '__main__':
	main()